mistic100/Photo-Sphere-Viewer

src/js/PSVUtils.js

"b" needs an offset to find the closing quote for the attribute, otherwise the opening quote will be found and the returned attribute value is null.

Added an offset to "b" to find the closing quotes

---

src/js/PSVUtils.js

This may be a more robust way to retrieve values from the XMP data. regex may allow for more reliable results over using substring.
With my Google Street View Panoramas shot on iPhone I was running into the following console errors:
```
THREE.WebGLRenderer: image is not power of two (0x0). Resized to 0x0 <canvas width=​"0" height=​"0">​
THREE.WebGLRenderer: Texture is not power of two. Texture.minFilter should be set to THREE.NearestFilter or THREE.LinearFilter. T…E.Texture {uuid: "894A673E-E8D7-4EF2-8B25-09154ED4AC33", name: "", sourceFile: "", image: canvas, mipmaps: Array[0]…}
WebGL: INVALID_VALUE: texImage2D: no canvas
```
Digging into the source it had to do with the substring failing to accurately extract the width and height from the XMP data.
My data:
```
<x:xmpmeta …
```

More robust retrieval of attributes.

---

package.json

**Changes**
When installing Photo-Sphere-Viewer via npm, the package fails to properly install and run since the dependency of three.js is n't in the packages.json. This adds it in to make Photo-Sphere-Viewer happy when installed for a project using npm.

Adding three dependancy.

---

src/js/PhotoSphereViewer.public.js
src/js/components/PSVHUD.js

- Fix animate method won't return a promise for duration 0. (Multiple return paths)
- Fix gotoMarker won't return a promise when the animation to marker finishes
IMO if we return a promise on animate we should always return a promise even if we don't need one because it can cause a fail when multiple promises are chained together. Also `animates` method sometimes return a promise and `gotoMarker` won't. The api should be more consistent. 

Improve animate and gotoMarker methods don't always return a promise

---

src/js/buttons/PSVNavBarZoomButton.js
src/js/components/PSVPanel.js

I remove the prevent bubling instructions on touchmove events for resizer and zoom slider because it blocks the scrolling of the lateral panel on mobile devices.
Tha problem can be see here: https://youtu.be/UsuCsb1vBBc
emulated with chrome.
As you can see, if you grab the panel in the gmaps iframe, it scrolls fine, but if you try on regular html you can't scroll.

Resolve: unable to scroll content panel on mobile device

---

src/js/PhotoSphereViewer.core.js
src/js/PhotoSphereViewer.defaults.js

Add 'with_credentials' parameter to PhotoSphereViewer constructor for sending AJAX requests with credentials so as to access secured pictures.

add with_credentials parameter

---

src/data/system.js

Hi!
I'm updating my code to use the new release of this library and I came across a compatibility problem with IE11 (not that we care a lot, but a lot of people on our website actually use it 😅).
Anyway, the visor was throwing an error indicating that WebGL was not supported, which was weird as we are using another library that uses it without any problem.
After taking a look at the code, it appears that the following fragment inside the `getWebGLCtx` method always returns after the first element inside the `names` array (**some** checks for the first "truthful").
```javascript
const names = ['webgl', 'experimental-webgl', 'moz-webgl', 'webkit-3d'];
[...code...]
names.some((name) => {
try {
context = canvas.getContext(name);
return true;
}
catch (e) {
return false;
}
});
```
According to …

Bugfix: getWebGLCtx was returning false on supported environments

---

docs/plugins/plugin-visible-range.md
src/plugins/visible-range/index.js

Make it easy to limit the visible range to the cropped panorama
data already set on the viewer with XMP or through panoData.
Another attempt at a fix for #476, without the messed up branch.
I have the getPanoLatitudeRange and getPanoLongitudeRange in my own code outside of the photo viewer so I know that it works in theory at least, but I have not tested this code in this repo. :grimacing: My JavaScript knowledge is a little, um, old-school, so I'm not sure how to actually build, run and test this here.
I have also only tested this code with images with XMP data (and images with no XMP data at all), I have not tested it with manually set panoData (using values or a callback).

Make it possible to use panoData in VisibleRanges plugin (attempt 2)

---

src/plugins/visible-range/index.js

The longitude range is 0 to 2*PI, but zero does not correspond
to the left edge of the full panorama, it corresponds to the
panorama's center.
Correct getPanoLongitudeRange() to return a range between
-PI (left edge) and +PI (right edge). setLongitudeRange()
converts this to values in the 0 to 2*PI range.
Fix for the bug I noticed after #478 got merged.

Correct VisibleRange longitudeRange for panoData

---

src/adapters/shared/AbstractVideoAdapter.js

* Update `playinline` to `playInline` to be able to read the **video** panorama on iOS without using the native iOS viewer.
There is a bug for iOS devices using the video plugin due to the missing attribute `playinline` during the html5 video tag creation [#L161](https://github.com/mistic100/Photo-Sphere-Viewer/blob/01d98377abd86b9c1183e2d9edbd97c6fd718918/src/adapters/shared/AbstractVideoAdapter.js#L161).
Tests examples of the issue from the [documentation](https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-video.html#example) using an iPhone on Chrome app:
I don't find good resources covering the issue. But it look like the attribute `playinline` should be in camelCase [#L161](https://github.com/mistic100/Photo-Sphere-Viewer/blob/01d98377abd86b9c1183e2d9edbd97c6fd718918/sr …

fix(iOS-video): display video adaptater on iOS

---

packages/markers-plugin/src/Marker.ts

Fixed a typo in `Marker.ts`.
It prevented markers having content but no tooltip to have the `cursor: pointer` attribute.
-   [x] All lints and tests pass.

Fix typo in Marker.ts

---

packages/core/src/buttons/DownloadButton.ts

This PR intends to change the current download button in navbar behaviour, to open offered image download in a new tab instead of redirecting current tab to image. Also fixes a typo in button classname.
-   [x] All lints and tests pass. If needed, new unit tests were added.
-   [x] If needed, the [documentation](https://github.com/mistic100/Photo-Sphere-Viewer/tree/main/docs) has been updated.

Download button opens in new tab

---

packages/core/src/services/TextureLoader.ts
packages/cubemap-tiles-adapter/src/CubemapTilesAdapter.ts
packages/equirectangular-tiles-adapter/src/EquirectangularTilesAdapter.ts
packages/markers-plugin/src/Marker.ts

-   [x] All lints and tests pass. If needed, new unit tests were added.
-   [x] If needed, the [documentation](https://github.com/mistic100/Photo-Sphere-Viewer/tree/main/docs) has been updated.
This PR offers a fix for authentication issue:
- When `Viewer` has parameter `withCredentials: true`
- And an adapter (like EquirectangularTilesAdapter) calls an image protected by credentials authentication (like cookies-based authentication)
- Happens on PSV 5.1.6, on at least Chromium 114 and Firefox 114 under Linux
Currently, adapters delegates loading to ThreeJS `Loader` using the `setWithCredentials` function. This is good, but apparently not enough for browsers: cookies containing authentication information are not sent for tiles. They happen to be sent for base …

Add crossOrigin use-credentials for ThreeJS loaders

---

docs/plugins/compass.md
packages/compass-plugin/src/CompassPlugin.ts
packages/compass-plugin/src/components/CompassComponent.ts
packages/compass-plugin/src/model.ts

-   [x] All lints and tests pass. If needed, new unit tests were added.
ClassName for compass. for example `position: [string, string]` may not ehough for positioning

chore: className for compass plugin

---

docs/plugins/markers.md
packages/markers-plugin/src/markers/Marker3D.ts
packages/markers-plugin/src/model.ts

These changes make it possible to disable the automatic playback of videoLayers. If you do this via an event listener and pause(), often it still throws unnecessary AbortError errors due to the autoplay policies of modern browsers.
To be backwards compatible, it defaults to autoplay enabled.
-   [x] All lints and tests pass. If needed, new unit tests were added.
-   [x] If needed, the [documentation](https://github.com/mistic100/Photo-Sphere-Viewer/tree/main/docs) has been updated.

Add autoplay option for videoLayer markers

---

docs/plugins/virtual-tour.md

-   [ ] All lints and tests pass. If needed, new unit tests were added.
The docs previously stated that the virtual-tour plugin `arrowStyle` config is only applicable in 3D mode, but that's incorrect. The `arrowStyle` config is applicable in both 2D and 3D mode.
This was clarified in https://github.com/mistic100/Photo-Sphere-Viewer/issues/1420#issuecomment-2327473908

docs(virtual-tour-plugin): Correct arrowStyle docs

---

docs/demos/markers/layers.md
docs/plugins/gallery.md
docs/plugins/map.md
docs/plugins/overlays.md
docs/plugins/plan.md
docs/plugins/virtual-tour.md
packages/core/src/data/constants.ts
packages/equirectangular-tiles-adapter/src/EquirectangularTilesAdapter.ts

-   [ ] All lints and tests pass. If needed, new unit tests were added.
A tiny typo fix.
I see many places in the docs where *below* is spelled as *bellow*, this PR attempts to fix that.

docs: Fix typo in docs and code comments

---

docs/guide/adapters/equirectangular-video.md
packages/shared/AbstractVideoAdapter.ts

-   [ ] All lints and tests pass. If needed, new unit tests were added.
I want to integrate PSV video plugin with the Hls.js and I need to access the html video element directly. So I modified the video adapter so that it accepts an HTMLVideoElement either.

Add HTMLVideoElement support for panorama video source

---

docs/plugins/markers.md

-   [ ] All lints and tests pass. If needed, new unit tests were added.
The link to the demo in the `elementLayer` section of the marker docs is invalid(extra `/` characters). This PR fixes that.

docs(marker-plugin): Fix broken link in docs

---

packages/shared/Queue.ts

-   [x] All lints and tests pass. If needed, new tests were added.
-   [x] If needed, the [documentation](https://github.com/mistic100/Photo-Sphere-Viewer/tree/main/docs) has been updated.
Possibility to control the loading queue concurrency for tiles adapter

Tile loading concurrency config
